<?php

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function gigya_page_attachments(array &$attachments) {
  // Add Settings.



  $attachments['#attached']['drupalSettings']['gigya']['globalParameters'] = \Drupal::config('gigya.global')->get('gigya.globalParameters');
  $attachments['#attached']['drupalSettings']['gigya']['enableRaaS'] = \Drupal::config('gigya.global')->get('gigya.enableRaaS');
  $attachments['#attached']['drupalSettings']['gigya']['apiKey'] = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');

  if (\Drupal::config('gigya.global')->get('gigya.enableRaaS') == TRUE) {
    if (\Drupal::currentUser()->isAnonymous()) {
      $raas_login = array(
        'screenSet' =>  'Default-RegistrationLogin',
        'mobileScreenSet' => 'DefaultMobile-RegistrationLogin',
        'startScreen' => 'gigya-login-screen',
      );
      $raas_register = array(
        'screenSet' => 'Default-RegistrationLogin',
        'mobileScreenSet' => 'DefaultMobile-RegistrationLogin',
        'startScreen' => 'gigya-register-screen',
      );
      //@TODO: add alter

      $attachments['#attached']['drupalSettings']['gigya']['raas']['login'] = $raas_login;
      $attachments['#attached']['drupalSettings']['gigya']['raas']['register'] = $raas_register;

    }
    else {
      $raas_profile = array(
        'screenSet' =>  'Default-ProfileUpdate',
        'mobileScreenSet' => 'DefaultMobile-ProfileUpdate'
      );
      $attachments['#attached']['drupalSettings']['gigya']['raas']['profile'] = $raas_profile;

    }
  }
  //@TODO: check config.
  $attachments['#attached']['drupalSettings']['gigya']['lang'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  // Add Library.
  $attachments['#attached']['library'][] = 'gigya/drupalGigya';

}

/**
 * Implements hook_theme().
 */
function gigya_theme($existing, $type, $theme, $path) {
  return array(
    'gigya_raas_links_block' => array(
      'variables' => array('links' => NULL, 'title' => NULL),
    ),
    'gigya_raas_login_block' => array(
      'variables' => array('showDiv' => NULL),
    ),
    'gigya_raas_register_block' => array(
      'variables' => array('showDiv' => NULL),
    ),
    'gigya_raas_profile_block' => array(
      'variables' => array('showDiv' => NULL),
    )
  );
}

/**
 * Implements hook_user_login().
 */
function gigya_user_login($account) {
  if (\Drupal::config('gigya.global')->get('gigya.enableRaaS') == TRUE) {
    if ($account->id() > 1 && !$account->hasPermission('bypass_gigya_raas')) {
      // If user didn't login via RaaS.
      // (if RaaS is enabled in Drupal admin, but a native login link was not disabled, and user still tried to login via Drupal login).
      global $rass_login;
      if ($rass_login == NULL) {
//        //@TODO: check if it is right.
        user_logout();
      }
    }
  }
}
