<?php

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function gigya_page_attachments(array &$attachments) {
  // Add Settings.
  $attachments['#attached']['drupalSettings']['gigya']['globalParameters'] = \Drupal::config('gigya.global')->get('gigya.globalParameters');
  $attachments['#attached']['drupalSettings']['gigya']['apiKey'] = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');
  //@TODO: check config.
  $attachments['#attached']['drupalSettings']['gigya']['lang'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  // Add Library.
  $attachments['#attached']['library'][] = 'gigya/drupalGigya';
}

/**
 * Implements hook_theme().
 */
function gigya_theme($existing, $type, $theme, $path) {
  return array(
    'gigya_raas_block' => array(
      'variables' => array('links' => NULL, 'title' => NULL),
    ),
  );
}



