<?php

define('GIGYA_DEFAULT_LOGINUI_WIDTH', '210');
define('GIGYA_DEFAULT_LOGINUI_HEIGHT', '110');
define('GIGYA_DEFAULT_LOGINUI_CONTAINERID', 'divGigyaLogin');
define('GIGYA_DEFAULT_CONNECTUI_WIDTH', '175');
define('GIGYA_DEFAULT_CONNECTUI_HEIGHT', '85');
define('GIGYA_DEFAULT_CONNECTUI_CONTAINERID', 'divConnect');
define('GIGYA_DEFAULT_CONNECTUI_CAPTIONTEXT', 'Select social networks');



/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function gigya_page_attachments(array &$attachments) {
  // Add Settings.
  $attachments['#attached']['drupalSettings']['gigya']['globalParameters'] = \Drupal::config('gigya.global')->get('gigya.globalParameters');
  $attachments['#attached']['drupalSettings']['gigya']['enableRaaS'] = \Drupal::config('gigya.global')->get('gigya.enableRaaS');
  $attachments['#attached']['drupalSettings']['gigya']['apiKey'] = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');


  $raas_login = array(
    'screenSet' =>  'Default-RegistrationLogin',
    'mobileScreenSet' => 'DefaultMobile-RegistrationLogin',
    'startScreen' => 'gigya-login-screen',
  );
  $raas_register = array(
    'screenSet' => 'Default-RegistrationLogin',
    'mobileScreenSet' => 'DefaultMobile-RegistrationLogin',
    'startScreen' => 'gigya-register-screen',
  );

  $attachments['#attached']['drupalSettings']['gigya']['raas']['login'] = $raas_login;
  $attachments['#attached']['drupalSettings']['gigya']['raas']['register'] = $raas_register;

  //@TODO: check config.
  $attachments['#attached']['drupalSettings']['gigya']['lang'] = \Drupal::languageManager()->getCurrentLanguage()->getId();

  // Add Library.
  $attachments['#attached']['library'][] = 'gigya/drupalGigya';

}

/**
 * Implements hook_theme().
 */
function gigya_theme($existing, $type, $theme, $path) {
  return array(
    'gigya_raas_links_block' => array(
      'variables' => array('links' => NULL, 'title' => NULL),
    ),
    'gigya_login_block' => array(
      'variables' => array('login_div' => NULL, 'title' => NULL),
    ),
  );
}

/**
 * Prepares variables for link templates.
 *
 * Default template: gigya-login-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *     - login_div: Contents of the login block.
 *     - title: Title to display, if not suppressed.
 */
function template_preprocess_gigya_login_block(&$variables) {
//  @TODO: check if we need this check :)
//  if (_gigya_is_component_enabled('login')) {
    $variables['login_div'] = gigya_loginui_js();
    if (!$variables['suppress_title']) {
      $variables['title'] = t('Login using social networks');
    }
//  }


}

/**
 * Gigya JavaScript settings for loginUI.
 *
 * Loads up the needed capabilities and variables for loginUI parameters.
 *
 * @return string
 *   The basic login ui if the gigya_login_advanced_raw variable
 *   is empty or the advanced login ui if not.
 */
function gigya_loginui_js() {
//  drupal_add_library('system', 'drupal.ajax');
//  ctools_include('ajax');
//  ctools_include('modal');
//  ctools_modal_add_js();
  static $index = 0;
  $width = GIGYA_DEFAULT_LOGINUI_WIDTH;
  $hieght = GIGYA_DEFAULT_LOGINUI_HEIGHT;
//  $width = variable_get('gigya_login_plugin_width', GIGYA_DEFAULT_LOGINUI_WIDTH);
//  $hieght = variable_get('gigya_login_plugin_height', GIGYA_DEFAULT_LOGINUI_HEIGHT);
//  $gigya_login_params = array(
//    'containerID' => variable_get('gigya_login_uiconfig_containerID', GIGYA_DEFAULT_LOGINUI_CONTAINERID),
//    'buttonsStyle' => variable_get('gigya_login_buttons_style', 'standard'),
//    'showTermsLink' => variable_get('gigya_login_uiconfig_terms', FALSE),
//    'width' => GIGYA_DEFAULT_LOGINUI_WIDTH,
//    'height' => GIGYA_DEFAULT_LOGINUI_HEIGHT,
//    'version' => 2
//  );
  $gigya_login_params = array(
    'containerID' => GIGYA_DEFAULT_LOGINUI_CONTAINERID,
    'buttonsStyle' => 'standard',
    'showTermsLink' => FALSE,
    'width' => GIGYA_DEFAULT_LOGINUI_WIDTH,
    'height' => GIGYA_DEFAULT_LOGINUI_HEIGHT,
    'version' => 2
  );
//  if (variable_get('gigya_login_plugin_size', FALSE)) {
//    $gigya_login_params['width'] = (int) $width;
//    $gigya_login_params['height'] = (int) $hieght;
//  }
  if ($index > 0) {
    $gigya_login_params['containerID'] .= '-' . $index;
  }
//   Merge configuration from advanced configuration.
//  $extra_login = variable_get('gigya_login_extra', array());
//  if (!empty($extra_login)) {
//    if (is_array($extra_login)) {
//      foreach ($extra_login as $key => $parm) {
//        $gigya_login_params[$key] = $parm;
//      }
//    }
//    else {
//      $gigya_login_params = array_merge($gigya_login_params, drupal_json_decode($extra_login));
//    }
//  }

  // Allow modules to alter the object before adding the JS to the page.
//  drupal_alter('gigya_loginui', $gigya_login_params);

//  drupal_add_js(array('gigya' => array('loginUIParams' => array($index => $gigya_login_params))), 'setting');
//  drupal_add_js(array('gigya' => array('loginDestination' => url('socialize-login', array('absolute' => TRUE)))), 'setting');

//  $index++;


  $build['div'] = array(
    '#type' => 'inline_template',
    '#template' => '<div class="gigya-social-login" id="{{ var }}"></div>',
    '#context' => array(
      'var' => GIGYA_DEFAULT_LOGINUI_CONTAINERID,
    ),
  );
  $build['div']['#attached']['drupalSettings']['gigya']['loginUIParams'][$index] = $gigya_login_params;
  return $build;
}
