<?php
use Drupal\gigya\Helper\GigyaHelper;
use Gigya\CmsStarterKit\sdk\GSObject;
/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function gigya_raas_page_attachments(array &$attachments) {
  // Add Settings.
  $api_key = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');
  if (!empty($api_key)) {
    $attachments['#attached']['drupalSettings']['gigya']['enableRaaS'] = \Drupal::config('gigya.global')->get('gigya.enableRaaS');

    if (\Drupal::config('gigya.global')->get('gigya.enableRaaS') == TRUE) {
      $session_mode = \Drupal::config('gigya.global')->get('gigya.sessionManagement');
      $attachments['#attached']['drupalSettings']['gigyaExtra']['isLogin'] = \Drupal::currentUser()->isAuthenticated();
      $attachments['#attached']['drupalSettings']['gigyaExtra']['sessionMode'] = $session_mode;
      if (\Drupal::currentUser()->isAnonymous()) {
        $raas_login = array(
          'screenSet' =>  'Default-RegistrationLogin',
          'mobileScreenSet' => '',
          'startScreen' => 'gigya-login-screen',
        );
        $raas_register = array(
          'screenSet' => 'Default-RegistrationLogin',
          'mobileScreenSet' => '',
          'startScreen' => 'gigya-register-screen',
        );
        \Drupal::moduleHandler()->alter('gigya_raas_settings', $raas_login, $raas_register);
        $attachments['#attached']['drupalSettings']['gigya']['raas']['login'] = $raas_login;
        $attachments['#attached']['drupalSettings']['gigya']['raas']['register'] = $raas_register;
        $attachments['#attached']['drupalSettings']['gigyaExtra'] = array('isLogin' => FALSE);
      }
      else {

        $attachments['#attached']['drupalSettings']['gigyaExtra']['bypassRaas'] = Drupal::currentUser()->hasPermission('bypass gigya raas');
        $raas_profile = array(
          'screenSet' =>  'Default-ProfileUpdate',
          'mobileScreenSet' => 'DefaultMobile-ProfileUpdate'
        );
        \Drupal::moduleHandler()->alter('gigya_raas_profile_settings', $raas_profile);
        $attachments['#attached']['drupalSettings']['gigya']['raas']['profile'] = $raas_profile;

        if ($session_mode == 'drupal' && !$attachments['#attached']['drupalSettings']['gigyaExtra']['bypassRaas']) {
          $gigya_apikey = trim(\Drupal::config('gigya.settings')->get('gigya.gigya_api_key'));
          if (!isset($_COOKIE["glt_$gigya_apikey"])) {
            //User is log in to drupal but not to gigya.
            //Need to notify login.

            $gigya_helper = new GigyaHelper();
            $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
            if ($guid = $user->uuid->value) {
              $cookie_params = session_get_cookie_params();
              $expire = $cookie_params['lifetime'] ? $cookie_params['lifetime'] : 0;
              $global_params = \Drupal::config('gigya.global')->get('gigya.globalParameters');
              if (isset($global_params['sessionExpiration']) && is_numeric($global_params['sessionExpiration'])) {
                $session_expire = $global_params['sessionExpiration'];
              }
              else {
                $session_expire = $expire;
              }
              $params = new GSObject();
              $params->put('siteUID', $guid);
              $params->put('sessionExpiration', $session_expire);
              $params->put('cid', 'cms relogin');

              $res = $gigya_helper->sendApiCall('accounts.notifyLogin', $params);

              if (!(get_class($res) == 'Gigya\CmsStarterKit\sdk\GSApiException')) {
                if (isset($res['sessionInfo'])) {
                  setcookie($res['sessionInfo']['cookieName'], $res['sessionInfo']['cookieValue']);
                }
              }
            }
          }
        }

      }
      $attachments['#attached']['library'][] = 'gigya_raas/gigyaRaas';
    }
  }
}

/**
 * Implements hook_theme().
 */
function gigya_raas_theme($existing, $type, $theme, $path) {
  return array(
    'gigya_raas_links_block' => array(
      'variables' => array('links' => NULL, 'title' => NULL),
    ),
    'gigya_raas_login_block' => array(
      'variables' => array('showDiv' => NULL),
    ),
    'gigya_raas_register_block' => array(
      'variables' => array('showDiv' => NULL),
    ),
    'gigya_raas_profile_block' => array(
      'variables' => array('showDiv' => NULL),
    )
  );
}

/**
 * Implements hook_user_login().
 */
function gigya_raas_user_login($account) {
  if (\Drupal::config('gigya.global')->get('gigya.enableRaaS') == TRUE) {
    if (!$account->hasPermission('bypass gigya raas')) {
      // If user didn't login via RaaS.
      // (if RaaS is enabled in Drupal admin, but a native login link was not disabled, and user still tried to login via Drupal login).
      global $raas_login;
      if ($raas_login == NULL) {
//        //@TODO: check if it is right.
        user_logout();
      }
    }
  }
}

function gigya_raas_user_logout($account) {
  $helper = new GigyaHelper();
  $helper->saveUserLogoutCookie();
}