<?php
use Drupal\gigya\Helper\GigyaHelper;

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function gigya_page_attachments(array &$attachments) {
  //Check for api key.
  $api_key = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');
  if (!empty($api_key)) {
    //Add gigya params to drupalSettings.
    $global_params = \Drupal::config('gigya.global')->get('gigya.globalParameters');

    $cookie_params = session_get_cookie_params();
    $expire = $cookie_params['lifetime'] ? $cookie_params['lifetime'] : 0;

    if (\Drupal::config('gigya.global')->get('gigya.sessionManagement') == 'drupal') {
      $gigya_js_settings['sessionExpiration'] = $expire;
    }

    \Drupal::moduleHandler()->alter('gigya_global_parameters', $global_params);

    $attachments['#attached']['drupalSettings']['gigya']['globalParameters'] = $global_params;
    $attachments['#attached']['drupalSettings']['gigya']['apiKey'] = \Drupal::config('gigya.settings')->get('gigya.gigya_api_key');

    $lang = \Drupal::config('gigya.global')->get('gigya.language');
    //Check if lang is in auto mode.
    if (strtolower($lang) == 'auto') {
      $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();

      $helper = new GigyaHelper();

      $languages = $helper->getGigyaLanguages();

      if (!array_key_exists($lang, $languages)) {
        //If we do not have the lang in gigya set the lang to the fallback.
        $lang = \Drupal::config('gigya.global')->get('gigya.languageFallback');
      }
    }

    \Drupal::moduleHandler()->alter('gigya_lang', $lang);
    $attachments['#attached']['drupalSettings']['gigya']['lang'] = $lang;

    // Add Library.
    $attachments['#attached']['library'][] = 'gigya/drupalGigya';

    $session_mode = \Drupal::config('gigya.global')->get('gigya.sessionManagement');
    // If the user is logged in then attach the Gigya object to the
    // user object.
    if (\Drupal::currentUser()->isAuthenticated()) {
      global $user;
      // Attach the Gigya object to the user object.
      GigyaUser::load($user);
      $bypass_raas = Drupal::currentUser()->hasPermission('bypass gigya raas');
      if ($session_mode == 'drupal') {
        $gigya_apikey = trim(Drupal::config('gigya.settings')->get('gigya.gigya_api_key'));
        if (!isset($_COOKIE["glt_$gigya_apikey"])) {
          //User is log in to drupal but not to gigya.
          //Need to notify login.

          $gigya_helper = new GigyaHelper();
          $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
          if ($guid = $user->uuid->value) {
            if (isset($gigya_js_settings['sessionExpiration']) && is_numeric($gigya_js_settings['sessionExpiration'])) {
              $session_expire = $gigya_js_settings['sessionExpiration'];
            }
            else {
              $session_expire = $expire;
            }

            $res = $gigya_helper->sendApiCall('accounts.notifyLogin', array('siteUID' => $guid, 'sessionExpiration' => $session_expire, 'cid' => 'cms relogin'));
            if (isset($res['sessionInfo'])) {
              setcookie($res['sessionInfo']['cookieName'], $res['sessionInfo']['cookieValue']);
            }
          }
        }
      }

      $attachments['#attached']['drupalSettings']['gigyaExtra']['isLogin'] = TRUE;
      $attachments['#attached']['drupalSettings']['gigyaExtra']['bypassRaas'] = $bypass_raas;
      $attachments['#attached']['drupalSettings']['gigyaExtra']['sessionMode'] = $session_mode;
    }
    else {
      $attachments['#attached']['drupalSettings']['gigyaExtra']['isLogin'] = FALSE;
      $attachments['#attached']['drupalSettings']['gigyaExtra']['sessionMode'] = $session_mode;
    }
  }
}