<?php

/**
 * Implements hook_gigya_global_parameters_alter().
 */
function gigya_client_gigya_global_parameters_alter(array &$gigya_global_parameters) {
  $gigya_global_parameters['bypassCookiePolicy'] = 'never';
}

/**
 * Implements hook_gigya_lang_alter().
 */
function gigya_client_gigya_lang_alter(&$lang) {
  $lang = "he";
}

/**
 * Implements hook_gigya_raas_settings_alter().
 */
function gigya_client_gigya_raas_settings_alter(array &$raas_login, array &$raas_register) {
  $raas_login['screenSet'] = 'Default-RegistrationLogin';
  $raas_login['mobileScreenSet'] = '';
  $raas_login['startScreen'] = 'gigya-login-screen';
}

/**
 * Implements hook_gigya_raas_profile_settings_alter().
 */
function gigya_client_gigya_raas_profile_settings_alter(array &$raas_profile) {
  $raas_profile['screenSet'] = 'Default-ProfileUpdate';
}